"""Update model Wallet

Revision ID: db75371bb787
Revises: 257ead437ca0
Create Date: 2025-07-21 10:29:34.259515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db75371bb787'
down_revision: Union[str, Sequence[str], None] = '257ead437ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'wallets', ['email'])
    op.drop_column('wallets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_column('wallets', 'email')
    # ### end Alembic commands ###
