"""update

Revision ID: 6165d62667f1
Revises: deaff6296ac5
Create Date: 2025-07-22 16:24:04.363848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6165d62667f1'
down_revision: Union[str, Sequence[str], None] = 'deaff6296ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'amount',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=2),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=19, scale=2),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('operations', 'amount',
               existing_type=sa.Numeric(precision=19, scale=2),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
