"""added field Wallet

Revision ID: 9c310b7c0c22
Revises: 5cf1fed8f79f
Create Date: 2025-07-20 22:30:26.044859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c310b7c0c22'
down_revision: Union[str, Sequence[str], None] = '5cf1fed8f79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'name')
    # ### end Alembic commands ###
