services:
  database:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/datad

volumes:
  postgres_data:
